### PR TITLE
hotfix bug where check box in founder spend funds was hidden

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by dangershony** [comment]
Hi @miladsoft why was this set as hidden? is it by mistake or you planned something else around the checkbox?

**Comment by dangershony** [comment]
before 

image


after 

image

**Comment by dangershony** [comment]
thanks @miladsoft

**Comment by dangershony** [comment]
no still not working

image

**Comment by miladsoft** [comment]
image

**Pull request merged**
